#!/usr/bin/env python3
import argparse
import difflib
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.checks.check_install_public_headers import STABLE_PUBLIC_HEADERS


DEFAULT_BASELINE = Path("tools/baselines/public_api_surface.txt")


def normalize_header_content(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def hash_header_content(text: str) -> str:
    normalized = normalize_header_content(text)
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def collect_public_api_surface(root: Path) -> list[str]:
    include_root = root / "include"
    surface: list[str] = []
    for relative_header in STABLE_PUBLIC_HEADERS:
        header = include_root / relative_header
        if not header.exists():
            surface.append(f"{relative_header}: <missing stable public header>")
            continue
        text = header.read_bytes().decode("utf-8-sig")
        surface.append(f"{relative_header}: sha256={hash_header_content(text)}")
    return surface


def baseline_text(surface: list[str]) -> str:
    header = [
        "# Generated by tools/checks/check_public_api_surface.py --print-current",
        "# SHA-256 of complete stable public headers after CRLF normalization.",
        "# Update deliberately when the supported public API changes.",
    ]
    return "\n".join([*header, *surface]) + "\n"


def read_baseline(path: Path) -> list[str]:
    lines = path.read_text(encoding="utf-8-sig").splitlines()
    return [line for line in lines if line and not line.startswith("#")]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--baseline", default=str(DEFAULT_BASELINE))
    parser.add_argument("--print-current", action="store_true")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    current = collect_public_api_surface(root)
    if args.print_current:
        print(baseline_text(current), end="")
        return 0

    baseline_path = (root / args.baseline).resolve()
    if not baseline_path.exists():
        print(f"missing public API surface baseline: {baseline_path}")
        return 1

    expected = read_baseline(baseline_path)
    if current == expected:
        print(f"status=PASS stable_headers={len(current)}")
        return 0

    diff = difflib.unified_diff(
        expected,
        current,
        fromfile=baseline_path.as_posix(),
        tofile="current-public-api-surface",
        lineterm="",
    )
    print("\n".join(diff))
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
